[package]
name = "rich-sdl2-rust"
version = "0.10.1"
authors = ["MikuroXina <ryosukadnak@gmail.com>"]
edition = "2021"
description = "The sdl2 wrapper for Rust."
repository = "https://github.com/MikuroXina/rich-sdl2-rust"
documentation = "https://mikuroxina.github.io/rich-sdl2-rust/rich_sdl2_rust/"
license = "Apache-2.0"
keywords = ["sdl2", "wrapper", "binding"]
categories = ["graphics", "gui", "multimedia", "rendering"]
rust-version = "1.56"

[features]
default = ["use_vcpkg"]
vulkan = ["ash"]
nightly = ["simd_allocator"]
simd_allocator = []
use_vcpkg = ["rich-sdl2-rust-sys/use_vcpkg"]
use_pkg_config = ["rich-sdl2-rust-sys/use_pkg_config"]

[dependencies]
ash = { version = "0.33.0", optional = true }
bitflags = "1.3.2"
static_assertions = "1.1.0"
typed-builder = "0.9.0"
rich-sdl2-rust-sys = { path = "./rich-sdl2-rust-sys", version = "0.2.0" }

[workspace]
members = ["rich-sdl2-rust-sys"]
