name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  BUILD_DIR: "${{ github.workspace }}/build/"

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows-static-md

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          vcpkgDirectory: "${{ github.workspace }}/vcpkg"
          appendedCacheKey: ${{ hashFiles( '**/vcpkg_manifest/vcpkg.json' ) }}
          additionalCachedPaths: ${{ env.BUILD_DIR }}/vcpkg_installed
          vcpkgTriplet: ${{ matrix.triplet }}
          vcpkgGitCommitId: 5568f110b509a9fd90711978a7cb76bae75bb092

      - name: Nightly with rustfmt and clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
          override: true

      - name: Install cargo-vcpkg
        run: cargo install cargo-vcpkg
      - name: Install dependencies
        run: cargo vcpkg -v build
        working-directory: ./rich-sdl2-rust-sys

      - name: Build crate
        run: cargo build --verbose
      - name: Clippy Check
        run: cargo clippy --verbose
      - name: Test crate
        run: cargo test --verbose
      - name: Create docs
        if: matrix.os == 'ubuntu-latest'
        run: cargo +nightly doc --all-features --no-deps

      - uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          name: doc-artifact
          path: target/doc/
